package domain;

/**
 * ECIPlant is a specialized type of Support plant.
 * It inherits from the Support class to provide specific behavior
 * and initial configuration compatible with the game's mechanics.
 */
public class ECIPlant extends Support{

    private int maxSolesGenerados = 3;
    private int solesGenerados = 0;

    /**
     * Constructs a new instance of ECIPlant with predefined attributes.
     * The ECIPlant is initialized with specified hit points, cost in sun points,
     * sun value generation rate, and generation interval.
     * It uses the superclass Support's constructor to provide these specific values:
     * hit points set to 150, sun cost to 75, a sun value of 50, and a time interval
     * of 20 seconds for sun generation.
     */
    public ECIPlant() {
        super(150,75,50,20);

    }


    /**
     * Generates a large sun if the maximum allowed number of suns has not
     * yet been reached. This method updates the internal counter
     * and prints a message indicating that a sun has been generated.
     * The maximum number of suns is determined by the `maxSolesGenerados` field.
     */
    public void generateSun() {
        if (solesGenerados < maxSolesGenerados) {
            System.out.println("Generando un sol grande...");
            solesGenerados++;
        }
    }

    /**
     * Checks if the current number of suns is zero and generates a sun
     * if the maximum number of generated suns has not been reached.
     *
     * @param currentSuns the current number of suns available. If this value
     *                    is zero, the method will attempt to generate a new sun.
     */
    public void checkAndGenerateSunWhenOutOfSuns(int currentSuns) {
        if (currentSuns == 0 && solesGenerados < maxSolesGenerados) {
            generateSun();
        }
    }
    /**
     * Retrieves the current number of suns generated by the ECIPlant.
     *
     * @return the current count of suns generated as an integer.
     */
    public int getSolesGenerados() {
        return solesGenerados;
    }
}
